{{- if eq .Values.deploymentMode "monolithic" }}
{{- $args := dict "ctx" . "component" "monolithic" "memberlist" true -}}
{{- $zonesMap := include "mimir.zoneAwareReplicationMap" $args | fromYaml -}}
{{- range $zoneName, $rolloutZone := $zonesMap }}
{{- with $ -}}
{{- $_ := set $args "rolloutZoneName" $zoneName -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mimir.resourceName" $args }}
  labels:
    {{- include "mimir.labels" $args | nindent 4 }}
  annotations:
    {{- include "mimir.componentAnnotations" $args | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  podManagementPolicy: {{ .Values.monolithic.podManagementPolicy }}
  replicas: {{ $rolloutZone.replicas }}
  {{- if and (semverCompare ">= 1.23-0" (include "mimir.kubeVersion" .)) (.Values.monolithic.persistentVolume.enableRetentionPolicy)  }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: {{ .Values.monolithic.persistentVolume.whenDeleted }}
    whenScaled: {{ .Values.monolithic.persistentVolume.whenScaled }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mimir.selectorLabels" $args | nindent 6 }}
  updateStrategy:
    {{- if $zoneName }}
    type: OnDelete
    {{- else }}
    {{- toYaml .Values.monolithic.statefulStrategy | nindent 4 }}
    {{- end }}
  serviceName: {{ template "mimir.fullname" . }}-monolithic{{- if not .Values.enterprise.legacyLabels -}}-headless{{- end -}}
  {{- if .Values.monolithic.persistentVolume.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: storage
        {{- if .Values.monolithic.persistentVolume.annotations }}
        annotations:
          {{- toYaml .Values.monolithic.persistentVolume.annotations | nindent 10 }}
        {{- end }}
      spec:
        {{- if .Values.monolithic.persistentVolume.storageClass }}
        {{- if (eq "-" .Values.monolithic.persistentVolume.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.monolithic.persistentVolume.storageClass }}"
        {{- end }}
        {{- end }}
        accessModes:
          {{- toYaml .Values.monolithic.persistentVolume.accessModes | nindent 10 }}
        resources:
          requests:
            storage: "{{ .Values.monolithic.persistentVolume.size }}"
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "mimir.podLabels" $args | nindent 8 }}
      annotations:
        {{- include "mimir.podAnnotations" $args | nindent 8 }}
      namespace: {{ .Release.Namespace | quote }}
    spec:
      {{- with .Values.monolithic.schedulerName }}
      schedulerName: {{ . | quote }}
      {{- end }}
      serviceAccountName: {{ template "mimir.serviceAccountName" . }}
      {{- if .Values.monolithic.priorityClassName }}
      priorityClassName: {{ .Values.monolithic.priorityClassName }}
      {{- end }}
      securityContext:
        {{- include "mimir.lib.podSecurityContext" $args | nindent 8 }}
      initContainers:
        {{- toYaml .Values.monolithic.initContainers | nindent 8 }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      nodeSelector:
        {{- $rolloutZone.nodeSelector | toYaml | nindent 8 }}
      affinity:
        {{- $rolloutZone.affinity | toYaml | nindent 8 }}
      {{- include "mimir.lib.topologySpreadConstraints" (dict "ctx" . "component" "monolithic") | nindent 6 }}
      tolerations:
        {{- toYaml .Values.monolithic.tolerations | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.monolithic.terminationGracePeriodSeconds }}
      volumes:
        - name: config
          {{- include "mimir.configVolume" . | nindent 10 }}
        {{- if .Values.enterprise.enabled }}
        - name: license
          secret:
            secretName: {{ tpl .Values.license.secretName . }}
        {{- end }}
        - name: runtime-config
          configMap:
            name: {{ template "mimir.fullname" . }}-runtime
        {{- if not .Values.monolithic.persistentVolume.enabled }}
        - name: storage
          emptyDir: {}
        {{- end }}
        {{- if .Values.monolithic.extraVolumes }}
        {{ toYaml .Values.monolithic.extraVolumes | nindent 8 }}
        {{- end }}
        - name: active-queries
          emptyDir: {}
        {{- if .Values.alertmanager.fallbackConfig }}
        - name: alertmanager-fallback-config
          configMap:
            name: {{ include "mimir.resourceName" (dict "ctx" . "component" "alertmanager") }}-fallback-config
        {{- end }}
      containers:
        {{- if .Values.monolithic.extraContainers }}
        {{ toYaml .Values.monolithic.extraContainers | nindent 8 }}
        {{- end }}
        - name: monolithic
          image: "{{ include "mimir.imageReference" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-target=all,alertmanager"
            - "-config.expand-env=true"
            - "-config.file=/etc/mimir/mimir.yaml"
            {{- if $zoneName }}
            - "-ingester.ring.instance-availability-zone={{ $zoneName }}"
            - "-store-gateway.sharding-ring.instance-availability-zone={{ $zoneName }}"
            {{- else }}
            - "-ingester.ring.instance-availability-zone=zone-default"
            {{- if .Values.monolithic.zoneAwareReplication.migration.enabled }}
            - "-blocks-storage.tsdb.flush-blocks-on-shutdown=true"
            - "-ingester.ring.unregister-on-shutdown=true"
            - "-store-gateway.sharding-ring.prefix=collectors/"
            - "-store-gateway.sharding-ring.zone-awareness-enabled=false"
            {{- end }}
            - "-server.grpc-max-concurrent-streams=500"
            {{- end }}
            - "-server.grpc.keepalive.max-connection-age=2562047h" # 100000 days, effectively infinity
            - "-server.grpc.keepalive.max-connection-age-grace=2562047h" # 100000 days, effectively infinity
            {{- if .Values.monolithic.compression.enabled }}
            - "-query-frontend.grpc-client-config.grpc-compression={{ .Values.monolithic.compression.algorithm }}"
            - "-query-scheduler.grpc-client-config.grpc-compression={{ .Values.monolithic.compression.algorithm }}"
            - "-ruler.client.grpc-compression={{ .Values.monolithic.compression.algorithm }}"
            - "-ruler.query-frontend.grpc-client-config.grpc-compression={{ .Values.monolithic.compression.algorithm }}"
            - "-ingester.client.grpc-compression={{ .Values.monolithic.compression.algorithm }}"
            {{- end }}
            {{- range $key, $value := .Values.monolithic.extraArgs }}
            - "-{{ $key }}={{ $value }}"
            {{- end }}
          volumeMounts:
            {{- if .Values.monolithic.extraVolumeMounts }}
            {{ toYaml .Values.monolithic.extraVolumeMounts | nindent 12}}
            {{- end }}
            - name: config
              mountPath: /etc/mimir
            - name: runtime-config
              mountPath: /var/{{ include "mimir.name" . }}
            - name: storage
              mountPath: "/data"
              {{- if .Values.monolithic.persistentVolume.subPath }}
              subPath: {{ .Values.monolithic.persistentVolume.subPath }}
              {{- else }}
              {{- end }}
            {{- if .Values.enterprise.enabled }}
            - name: license
              mountPath: /license
            {{- end }}
            - name: active-queries
              mountPath: /active-query-tracker
            {{- if .Values.alertmanager.fallbackConfig }}
            - name: alertmanager-fallback-config
              mountPath: /configs/
            {{- end }}
          ports:
            - name: http-metrics
              containerPort: {{ include "mimir.serverHttpListenPort" . }}
              protocol: TCP
            - name: grpc
              containerPort: {{ include "mimir.serverGrpcListenPort" . }}
              protocol: TCP
            - name: memberlist
              containerPort: {{ include "mimir.memberlistBindPort" . }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.monolithic.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.monolithic.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.monolithic.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.monolithic.containerSecurityContext | nindent 12 }}
          env:
            {{- with .Values.global.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.monolithic.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            {{- with .Values.global.extraEnvFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.monolithic.extraEnvFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
---
{{ end }}
{{ end }}
{{ end }}